import { mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { expect, test } from 'vitest'
import { createContext } from '../src/core/ctx'

test('dts', async () => {
  const cwd = join(__dirname, 'fixtures/base')
  const ctx = createContext({})

  ctx.init(cwd)
  ctx.scanEasyComponents()
  ctx.generateTypeDeclarations()

  const dts = join(cwd, 'src/uniapp-easycom.d.ts')

  expect((await stat(dts)).isFile()).toBe(true)

  const dtsContent = await readFile(dts, 'utf-8')
  expect(dtsContent).toMatchInlineSnapshot(`
    "/* eslint-disable */
    /* prettier-ignore */
    // @ts-nocheck
    // noinspection JSUnusedGlobalSymbols
    // Generated by uniapp-easycom-types
    // biome-ignore lint: disable
    export {}
    declare module 'vue' {
      export interface GlobalComponents {
        UniList: (typeof import('./uni_modules/uni-list/components/uni-list/uni-list.vue'))['default']
        ComA: (typeof import('./components/com-a/com-a.vue'))['default']
      }
    }"
  `)

  await rm(dts)
})

test('custom dts', async () => {
  const cwd = join(__dirname, 'fixtures/base')
  const customDts = 'src/types/uniapp-easycom.d.ts'
  const ctx = createContext({
    dts: customDts,
  })

  ctx.init(cwd)
  ctx.scanEasyComponents()
  ctx.generateTypeDeclarations()

  const dts = join(cwd, customDts)

  expect((await stat(dts)).isFile()).toBe(true)

  await rm(dirname(dts), { recursive: true })
})

test('custom easycom', async () => {
  const cwd = join(__dirname, 'fixtures/custom')

  // Simulate installation node_modules
  const packageVueFile = 'node_modules/packageName/path/to/vue-file-list.vue'
  await mkdir(join(cwd, dirname(packageVueFile)), { recursive: true })
  await writeFile(join(cwd, packageVueFile), '', 'utf-8')

  const ctx = createContext({})

  ctx.init(cwd)
  ctx.scanEasyComponents()
  ctx.generateTypeDeclarations()

  const dts = join(cwd, 'src/uniapp-easycom.d.ts')

  expect((await stat(dts)).isFile()).toBe(true)

  const dtsContent = await readFile(dts, 'utf-8')
  expect(dtsContent).toMatchInlineSnapshot(`
    "/* eslint-disable */
    /* prettier-ignore */
    // @ts-nocheck
    // noinspection JSUnusedGlobalSymbols
    // Generated by uniapp-easycom-types
    // biome-ignore lint: disable
    export {}
    declare module 'vue' {
      export interface GlobalComponents {
        UniComA: (typeof import('./components/uni-com-a.vue'))['default']
        VueFileList: (typeof import('../node_modules/packageName/path/to/vue-file-list.vue'))['default']
      }
    }"
  `)

  await rm(dts)

  // Uninstall node_modules
  await rm(join(cwd, 'node_modules'), { recursive: true })
})
