import { existsSync, readFileSync, unlinkSync } from 'node:fs'
import { join } from 'node:path'
import { expect, test } from 'vitest'
import { createContext } from '../src/core/ctx'

test('dts', () => {
  const cwd = join(__dirname, 'fixtures/base')
  const ctx = createContext({})

  ctx.init(cwd)
  ctx.scanEasyComponents()
  ctx.generateTypeDeclarations()

  const dts = join(cwd, 'src/easycom.d.ts')

  expect(existsSync(dts)).toBe(true)

  const dtsContent = readFileSync(dts, 'utf-8')
  expect(dtsContent).toMatchInlineSnapshot(`
    "/* eslint-disable */
    /* prettier-ignore */
    // @ts-nocheck
    // noinspection JSUnusedGlobalSymbols
    // Generated by uniapp-easycom
    // biome-ignore lint: disable
    export {}
    declare module 'vue' {
      export interface GlobalComponents {
        UniList: (typeof import('./uni_modules/uni-list/components/uni-list/uni-list.vue'))['default']
        ComA: (typeof import('./components/com-a/com-a.vue'))['default']
      }
    }"
  `)

  unlinkSync(dts)
})

test('custom dts', () => {
  const cwd = join(__dirname, 'fixtures/base')
  const customDts = 'src/types/easycom.d.ts'
  const ctx = createContext({
    dts: customDts,
  })

  ctx.init(cwd)
  ctx.scanEasyComponents()
  ctx.generateTypeDeclarations()

  const dts = join(cwd, customDts)

  expect(existsSync(dts)).toBe(true)
  unlinkSync(dts)
})
